-- 甜老板发卡站 · Supabase 建表 SQL
-- 使用：Supabase Dashboard → SQL Editor → 粘贴全部 → Run

-- 1) 卡密库存
create table if not exists shop_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  status text not null default 'unused',   -- unused / sold
  order_no text,
  created_at timestamptz default now(),
  sold_at timestamptz
);

-- 2) 订单
create table if not exists shop_orders (
  id bigint generated by default as identity primary key,
  order_no text not null unique,
  status text not null default 'pending',  -- pending / paid / delivered
  amount text default '9.90',
  code text,
  created_at timestamptz default now(),
  paid_at timestamptz
);

-- 3) 激活码设备绑定（工具端用：一码一设备 + 1 次换绑）
create table if not exists code_bindings (
  code text primary key,
  device_id text not null,
  swap_count int not null default 0,
  updated_at timestamptz default now()
);

-- 开放匿名访问（发卡站/工具端都是无登录前端）
drop policy if exists "pub codes" on shop_codes;
create policy "pub codes" on shop_codes for all to anon using (true) with check (true);

drop policy if exists "pub orders" on shop_orders;
create policy "pub orders" on shop_orders for all to anon using (true) with check (true);

drop policy if exists "pub bindings" on code_bindings;
create policy "pub bindings" on code_bindings for all to anon using (true) with check (true);
